finos/SwiftSearch

package.json, src/utils/checkDiskSpace.ts
Electron "child_process" promisify issue
[SEARCH-905](https://perzoinc.atlassian.net/browse/SEARCH-905)
Electron "child_process" promisify issue was fixed in `electron 2.0.7` bumping the electron version and changes the method ti use promisify
N/A
branch | PR
SymphonyElectron | [link](https://github.com/symphonyoss/SymphonyElectron/pull/462)
[Test Results — Search.pdf](https://github.com/symphonyoss/SwiftSearch/files/2282377/Test.Results.Search.pdf)
=> SEARCH-905 (Electron "child_process" promisify issue)

package.json, src/search.ts, src/searchLibrary.ts, src/utils/searchUtils.ts
Revert back to ffi (ffi-napi - napi_get_uv_event_loop issue on windows)
[SEARCH-915](https://perzoinc.atlassian.net/browse/SEARCH-915)
branch | PR
SymphonyElectron | [link]()
[Test Results — Search.pdf](https://github.com/symphonyoss/SwiftSearch/files/2313492/Test.Results.Search.pdf)
=> SEARCH-915 Revert back to ffi (ffi-napi - napi_get_uv_event_loop issue on windows)

package.json
Security vulnerability in 2.0.7
=> Bump electron version to 3.0.0-beta.7

package.json
Change node-ffi base fork to symphonyoss
Attach unit in PDF format against the above task lists for this branch
=> Change node-ffi base fork to symphonyoss

index.ts, src/interface/interface.ts, src/searchAPIBridge.ts
SEARCH-1313 (Initial Setup for Context Isolation) 
[SEARCH-1313](https://perzoinc.atlassian.net/browse/SEARCH-1313)
Changes bridge b/w electron SFE via postMessage
N/A
N/A
=> SEARCH-1313 (Initial Setup for Context Isolation)

package.json, src/search.ts, src/searchLibrary.ts
- ffi → ffi-napi
- ref → ref-napi
- bump version to 5.0.0-beta.1
=> Update dependencies to node version 12 

package.json, src/interface/interface.ts, src/search.ts, src/searchAPIBridge.ts, src/searchLibrary.ts, tslint.json
Context Isolation Implementation - Integrating With SFE
[SEARCH-1410](https://perzoinc.atlassian.net/browse/SEARCH-1410)
Creates a custom post message which returns promise.
N/A
branch | PR
other_pr_dev | [link]()
- [] Unit-Tests
=> SEARCH-1410 (Context Isolation Implementation - Integrating With SFE)

.npmignore, package.json, src/interface/interface.ts, src/search.ts, src/searchAPIBridge.ts
Complete workflow of context-isolation
[SEARCH-1428](https://perzoinc.atlassian.net/browse/SEARCH-1428)
[SEARCH-1313](https://perzoinc.atlassian.net/browse/SEARCH-1313)
N/A
N/A
branch | PR
SymphonyElectron | [#632](https://github.com/symphonyoss/SymphonyElectron/pull/632)
- [] Unit-Tests
Attach unit in PDF format against the above task lists for this branch
=> SEARCH-1428 (Complete workflow of context-isolation)

tests/SearchContextIsolation.test.ts
Unit tests for context-isolation implementation
[SEARCH-1460](https://perzoinc.atlassian.net/browse/SEARCH-1460)
Story
[SEARCH-1313](https://perzoinc.atlassian.net/browse/SEARCH-1313)
N/A
N/A
N/A
[Test Results — Tests for Search Context-Isolation PostMessage.pdf](https://github.com/symphonyoss/SwiftSearch/files/3172403/Test.Results.Tests.for.Search.Context-Isolation.PostMessage.pdf)
=> SEARCH-1460 - Unit tests for context-isolation implementation

.npmignore, index.ts, package.json, src/interface/interface.ts, src/search.ts, src/searchAPIBridge.ts, src/searchLibrary.ts, tests/SearchContextIsolation.test.ts, tslint.json
Context-Isolation changes to the master
[SEARCH-1313](https://perzoinc.atlassian.net/browse/SEARCH-1313)
`1.55.1` has already been cut from master
N/A
N/A
N/A
=> [Merge] Context-Isolation changes to master

package.json, src/interface/interface.ts, src/search.ts, src/searchAPIBridge.ts, src/searchConfig.ts, tests/Search.test.ts, tests/SearchContextIsolation.test.ts
Include Index-Validator for verifying the index.
[SEARCH-1514](https://perzoinc.atlassian.net/browse/SEARCH-1514)
When we initialize the corrupted index it crashes the electron app. So in order to prevent unexpected crashes, we validate the index before initializing.  
List related PRs against other branches/repositories:
branch | PR
SymphonyElectron `master` | [#669](https://github.com/symphonyoss/SymphonyElectron/pull/669)
SymphonyElectron `5.x` | [#670](https://github.com/symphonyoss/SymphonyElectron/pull/670)
=> feat: SEARCH-1514 - Include Index-Validator for verifying the index

.gitignore, package.json, src/search.ts, src/searchLibrary.ts
=> Revert ffi napi

package.json, src/interface/interface.ts, src/search.ts, src/searchAPIBridge.ts, src/searchConfig.ts, src/utils/checkDiskSpace.ts, src/utils/searchUtils.ts, tests/Search.test.ts
Remove FreeDiskSpace which was dependant on .Net
And pass minimum disk space from SFE
[SEARCH-1541](https://perzoinc.atlassian.net/browse/SEARCH-1541)
[comment]: # (How does this change address the problem?)
- N/A
- Passing the minimum disk space required for swift-search from SFE as arg.
N/A
N/A
[comment]: # (List the related PRs against other branches.)
Repo | Branch | PR #
------ | ------ | ------
SFE | branch-name | [#15257](https://github.com/SymphonyOSF/SFE-Client-App/pull/15257)
SFE-Context-Isolation | branch-name | [#8](https://github.com/KiranNiranjan/SFE-Client-App/pull/8)
SymphonyElectron | branch-name | [#692](https://github.com/symphonyoss/SymphonyElectron/pull/692)
[comment]: # (When resolved, check the box and explain the answer.)
N/A
=> feat: SEARCH-1541 - Change FreeDiskSpace to use native binding

demo/search.html, package.json, src/interface/interface.ts, src/search.ts, src/searchAPIBridge.ts
Swift Search ThreadAPI client interaction with throttling
[SEARCH-1565](https://perzoinc.atlassian.net/browse/SEARCH-1565)
[SEARCH-1564](https://perzoinc.atlassian.net/browse/SEARCH-1564)
Please refer implementation doc here -> https://perzoinc.atlassian.net/wiki/spaces/SEARCH/pages/595788140/Swift+Search+-+Throttling+ThreadAPI+for+Request+Bursts
[comment]: # (How does this change address the problem?)
N/A
N/A
N/A
N/A
[comment]: # (List the related PRs against other branches.)
Repo | Branch | PR #
------ | ------ | ------
SFE-Client-App | branch-name | [PR #15380](https://github.com/SymphonyOSF/SFE-Client-App/pull/15380)
SymphonyElectron | branch-name | [PR #698](https://github.com/symphonyoss/SymphonyElectron/pull/698)
[comment]: # (When resolved, check the box and explain the answer.) …
=> SEARCH-1565 - Swift Search - ThreadAPI client interaction with throttling

package.json, src/search.ts
Add safety check for deleting real-time index (safety check)
N/A
N/A
branch | PR
SymphonyElectron | [link]()
=> Add safety check for deleting real-time index (safety check)

package.json
Bump release version `1.55.3-rc.1`
N/A
N/A
branch | PR
SymphonyElectron | [#706](https://github.com/symphonyoss/SymphonyElectron/pull/706)
- [] Unit-Tests
=> Bump release version `1.55.3-rc.1`

package.json, src/search.ts
Fix sort order check.
[JIRA-ticket](https://perzoinc.atlassian.net/browse/JIRA-ticket)
N/A
N/A
branch | PR
SymhonyElectron | [#723](https://github.com/symphonyoss/SymphonyElectron/pull/723)
SFE-Client-App | [link]()
=> fix: SEARCH-1582 - Fix sort order check

package.json, src/searchConfig.ts, tests/Search.test.ts, tests/SearchContextIsolation.test.ts
Bump index-version & Fix large index size
branch | PR
SymphonyElectron | [#739](https://github.com/symphonyoss/SymphonyElectron/pull/739)
=> fix: Bump index-version & Fix large index size (With libraries)

package.json, src/search.ts
[SEARCH-1646](https://perzoinc.atlassian.net/browse/SEARCH-1646) - Add safety check for the dictionary file
=> SEARCH-1646 - Add safety check for the dictionary file

package.json, src/search.ts
SEARCH-1646 - Add missing class instance
=> SEARCH-1646 - Add missing class instance

index.ts, src/mana/bridge.ts
Exposing the SwiftSearch API via `contextBridge`
Exposes all the API from the library and SearchUtils.
_**Note: Creating a Feature branch to have this merged once all the changes are ready on the SFE-Lite side.**_
=> Swift Search Implementation for Mana client

package.json
=> update disk-usage dependency

package.json
Bump electron version to 9.4.1
=> electron security vulnerabilities fix
